package tdx

import (
	"encoding/binary"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

// =============================================================================
// parseTDXQuote
// =============================================================================

func TestParseTDXQuote_V4Valid(t *testing.T) {
	t.Parallel()
	wantMRTD := defaultTestMRTD()
	wantRTMRs := defaultTestRTMRs()
	q := synthV4TDXQuote([]byte("rd"), wantMRTD, wantRTMRs)

	parsed, err := parseTDXQuote(q)
	require.NoError(t, err)
	require.Equal(t, uint16(4), parsed.Version)
	require.Equal(t, teeTypeTDX, parsed.TeeType)
	require.Equal(t, wantMRTD, parsed.MRTD)
	require.Equal(t, wantRTMRs[0], parsed.RTMR0)
	require.Equal(t, wantRTMRs[1], parsed.RTMR1)
	require.Equal(t, wantRTMRs[2], parsed.RTMR2)
	require.Equal(t, wantRTMRs[3], parsed.RTMR3)
	require.Len(t, parsed.ReportData, tdxReportDataSize)
	require.Equal(t, byte('r'), parsed.ReportData[0])
	require.Equal(t, byte('d'), parsed.ReportData[1])
}

func TestParseTDXQuote_V5Valid(t *testing.T) {
	t.Parallel()
	q := synthV5TDXQuote(nil, defaultTestMRTD(), defaultTestRTMRs())
	parsed, err := parseTDXQuote(q)
	require.NoError(t, err)
	require.Equal(t, uint16(5), parsed.Version)
	require.Len(t, q, minQuoteSizeTD15)
	require.Len(t, parsed.MRTD, sizeMeasurement)
	require.Len(t, parsed.RTMR3, sizeMeasurement)
}

func TestParseTDXQuote_TruncatedHeader(t *testing.T) {
	t.Parallel()
	q := make([]byte, 10)
	_, err := parseTDXQuote(q)
	require.ErrorContains(t, err, "quote too short for header")
}

func TestParseTDXQuote_TruncatedBody(t *testing.T) {
	t.Parallel()
	q := synthV4TDXQuote(nil, defaultTestMRTD(), defaultTestRTMRs())
	short := q[:200]
	_, err := parseTDXQuote(short)
	require.ErrorContains(t, err, "quote too short for v4 body")
}

func TestParseTDXQuote_WrongTeeType(t *testing.T) {
	t.Parallel()
	q := synthV4TDXQuote(nil, defaultTestMRTD(), defaultTestRTMRs())
	// Overwrite tee_type to SGX value.
	binary.LittleEndian.PutUint32(q[quoteOffTeeType:], teeTypeSGX)
	_, err := parseTDXQuote(q)
	require.ErrorContains(t, err, "not a TDX quote")
}

func TestParseTDXQuote_UnsupportedVersion(t *testing.T) {
	t.Parallel()
	q := synthV4TDXQuote(nil, defaultTestMRTD(), defaultTestRTMRs())
	binary.LittleEndian.PutUint16(q[quoteOffVersion:], 3)
	_, err := parseTDXQuote(q)
	require.ErrorContains(t, err, "unsupported quote version")
}

func TestParseTDXQuote_DefensiveCopy(t *testing.T) {
	t.Parallel()
	q := synthV4TDXQuote(nil, defaultTestMRTD(), defaultTestRTMRs())
	parsed1, err := parseTDXQuote(q)
	require.NoError(t, err)

	// Mutate the parsed slice; re-parse and check the second result is
	// independent of the first.
	parsed1.MRTD[0] = 0xFF

	parsed2, err := parseTDXQuote(q)
	require.NoError(t, err)
	require.NotEqual(t, parsed1.MRTD, parsed2.MRTD)
	require.Equal(t, defaultTestMRTD(), parsed2.MRTD)
}

// =============================================================================
// cloneSlice / isZero
// =============================================================================

func TestCloneSlice_Independent(t *testing.T) {
	t.Parallel()
	a := []byte{1, 2, 3}
	b := cloneSlice(a)
	require.Equal(t, a, b)
	b[0] = 9
	require.NotEqual(t, a, b)
}

func TestCloneSlice_Empty(t *testing.T) {
	t.Parallel()
	out := cloneSlice(nil)
	require.NotNil(t, out)
	require.Empty(t, out)
}

func TestIsZero(t *testing.T) {
	t.Parallel()
	require.True(t, isZero(nil))
	require.True(t, isZero([]byte{0, 0, 0}))
	require.False(t, isZero([]byte{0, 0, 1}))
}

// =============================================================================
// V4 fast-path coverage with a production-shape quote.
//
// Synthetic quotes generated by synthV4TDXQuote are intentionally minimal
// (header + body only) and do NOT pass abi.QuoteToProto's QuoteMinSize
// check, so they always exercise the parseTDXQuoteManual fallback. The
// fixture below is a real Sapphire Rapids TDX quote (full DCAP envelope)
// used to exercise the parseTDXQuoteV4 success path. See testdata/README.md
// for the source and licensing.
// =============================================================================

// TestParseTDXQuoteV4_RealQuote ensures the abi.QuoteToProto fast path
// returns a parsedTDXQuote whose measurement fields have the documented
// shapes (48B MRTD, 48B RTMR0..3, 64B ReportData) and whose TeeType matches
// teeTypeTDX. It also asserts CodeCommitment-relevant fields are non-zero,
// matching what real TDX hardware emits.
func TestParseTDXQuoteV4_RealQuote(t *testing.T) {
	t.Parallel()
	raw, err := os.ReadFile(filepath.Join("testdata", "tdx_prod_quote_SPR_E4.dat"))
	require.NoError(t, err)

	parsed, err := parseTDXQuoteV4(raw)
	require.NoError(t, err)
	require.Equal(t, uint16(4), parsed.Version)
	require.Equal(t, teeTypeTDX, parsed.TeeType)
	require.Len(t, parsed.MRTD, sizeMeasurement)
	require.Len(t, parsed.RTMR0, sizeMeasurement)
	require.Len(t, parsed.RTMR1, sizeMeasurement)
	require.Len(t, parsed.RTMR2, sizeMeasurement)
	require.Len(t, parsed.RTMR3, sizeMeasurement)
	require.Len(t, parsed.ReportData, tdxReportDataSize)
	require.False(t, isZero(parsed.MRTD), "real TDX MRTD must not be all-zero")
}

// TestParseTDXQuote_RealQuote_DispatchesToV4Path confirms the top-level
// parseTDXQuote dispatcher selects the V4 fast path for a real quote (i.e.,
// abi.QuoteToProto succeeds, and the manual fallback is not reached). The
// observable signature is the same parsed measurements; this test exists so
// a future regression that broke the fast path (e.g., a constant change or
// abi behavior change) would not silently re-route every real quote through
// the manual parser without a coverage signal.
func TestParseTDXQuote_RealQuote_DispatchesToV4Path(t *testing.T) {
	t.Parallel()
	raw, err := os.ReadFile(filepath.Join("testdata", "tdx_prod_quote_SPR_E4.dat"))
	require.NoError(t, err)

	parsed, err := parseTDXQuote(raw)
	require.NoError(t, err)
	require.Equal(t, uint16(4), parsed.Version)
	require.Equal(t, teeTypeTDX, parsed.TeeType)
	require.Len(t, parsed.MRTD, sizeMeasurement)
}

// =============================================================================
// Fuzz tests
// =============================================================================

// FuzzParseTDXQuoteBody fuzzes parseTDXQuote with arbitrary byte slices to
// catch panics, infinite loops, and out-of-bounds reads. The seed corpus
// covers both valid V4/V5 quotes and various truncated/empty inputs so the
// fuzzer immediately exercises every length-check branch in the parser.
func FuzzParseTDXQuoteBody(f *testing.F) {
	// Valid V4 / V5 inputs.
	f.Add(synthV4TDXQuote([]byte{0}, defaultTestMRTD(), defaultTestRTMRs()))
	f.Add(synthV5TDXQuote([]byte{0}, defaultTestMRTD(), defaultTestRTMRs()))
	// Boundary truncations.
	f.Add([]byte{})
	f.Add(make([]byte, 1))
	f.Add(make([]byte, quoteHeaderSizeTDX-1))
	f.Add(make([]byte, quoteHeaderSizeTDX))
	f.Add(make([]byte, minQuoteSizeTD10-1))
	f.Add(make([]byte, minQuoteSizeTD10))
	// Random shape.
	f.Add(append([]byte{0xFF, 0xFF, 0xFF, 0xFF}, make([]byte, 700)...))

	f.Fuzz(func(t *testing.T, quote []byte) {
		parsed, err := parseTDXQuote(quote)
		if err != nil {
			if parsed != nil {
				t.Fatalf("parser returned both result and error: %v", err)
			}
			return
		}
		if len(parsed.MRTD) != sizeMeasurement {
			t.Fatalf("MRTD length = %d, want %d", len(parsed.MRTD), sizeMeasurement)
		}
		for i, r := range [][]byte{parsed.RTMR0, parsed.RTMR1, parsed.RTMR2, parsed.RTMR3} {
			if len(r) != sizeMeasurement {
				t.Fatalf("RTMR%d length = %d, want %d", i, len(r), sizeMeasurement)
			}
		}
		if len(parsed.ReportData) != tdxReportDataSize {
			t.Fatalf("ReportData length = %d, want %d", len(parsed.ReportData), tdxReportDataSize)
		}
	})
}
