// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: deal.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptedDeal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DhKey         []byte                 `protobuf:"bytes,1,opt,name=dh_key,proto3" json:"dh_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Cipher        []byte                 `protobuf:"bytes,4,opt,name=cipher,proto3" json:"cipher,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedDeal) Reset() {
	*x = EncryptedDeal{}
	mi := &file_deal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedDeal) ProtoMessage() {}

func (x *EncryptedDeal) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedDeal.ProtoReflect.Descriptor instead.
func (*EncryptedDeal) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedDeal) GetDhKey() []byte {
	if x != nil {
		return x.DhKey
	}
	return nil
}

func (x *EncryptedDeal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *EncryptedDeal) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedDeal) GetCipher() []byte {
	if x != nil {
		return x.Cipher
	}
	return nil
}

type Deal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	RecipientIndex uint32                 `protobuf:"varint,2,opt,name=recipient_index,proto3" json:"recipient_index,omitempty"`
	Deal           *EncryptedDeal         `protobuf:"bytes,3,opt,name=deal,proto3" json:"deal,omitempty"`
	Signature      []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Deal) Reset() {
	*x = Deal{}
	mi := &file_deal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deal) ProtoMessage() {}

func (x *Deal) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deal.ProtoReflect.Descriptor instead.
func (*Deal) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{1}
}

func (x *Deal) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Deal) GetRecipientIndex() uint32 {
	if x != nil {
		return x.RecipientIndex
	}
	return 0
}

func (x *Deal) GetDeal() *EncryptedDeal {
	if x != nil {
		return x.Deal
	}
	return nil
}

func (x *Deal) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	VssResponse   *VSSResponse           `protobuf:"bytes,2,opt,name=vss_response,proto3" json:"vss_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_deal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Response) GetVssResponse() *VSSResponse {
	if x != nil {
		return x.VssResponse
	}
	return nil
}

type VSSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,proto3" json:"session_id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VSSResponse) Reset() {
	*x = VSSResponse{}
	mi := &file_deal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VSSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSSResponse) ProtoMessage() {}

func (x *VSSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSSResponse.ProtoReflect.Descriptor instead.
func (*VSSResponse) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{3}
}

func (x *VSSResponse) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *VSSResponse) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *VSSResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *VSSResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Justification struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Index            uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	VssJustification *VSSJustification      `protobuf:"bytes,2,opt,name=vss_justification,proto3" json:"vss_justification,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Justification) Reset() {
	*x = Justification{}
	mi := &file_deal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Justification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Justification) ProtoMessage() {}

func (x *Justification) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Justification.ProtoReflect.Descriptor instead.
func (*Justification) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{4}
}

func (x *Justification) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Justification) GetVssJustification() *VSSJustification {
	if x != nil {
		return x.VssJustification
	}
	return nil
}

type VSSJustification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,proto3" json:"session_id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	PlainDeal     *PlainDeal             `protobuf:"bytes,3,opt,name=plain_deal,proto3" json:"plain_deal,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VSSJustification) Reset() {
	*x = VSSJustification{}
	mi := &file_deal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VSSJustification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VSSJustification) ProtoMessage() {}

func (x *VSSJustification) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VSSJustification.ProtoReflect.Descriptor instead.
func (*VSSJustification) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{5}
}

func (x *VSSJustification) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *VSSJustification) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *VSSJustification) GetPlainDeal() *PlainDeal {
	if x != nil {
		return x.PlainDeal
	}
	return nil
}

func (x *VSSJustification) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PlainDeal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     []byte                 `protobuf:"bytes,1,opt,name=session_id,proto3" json:"session_id,omitempty"`
	SecShare      *SecShare              `protobuf:"bytes,2,opt,name=sec_share,proto3" json:"sec_share,omitempty"`
	Threshold     uint32                 `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Commitments   []*Point               `protobuf:"bytes,4,rep,name=commitments,proto3" json:"commitments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlainDeal) Reset() {
	*x = PlainDeal{}
	mi := &file_deal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlainDeal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlainDeal) ProtoMessage() {}

func (x *PlainDeal) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlainDeal.ProtoReflect.Descriptor instead.
func (*PlainDeal) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{6}
}

func (x *PlainDeal) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *PlainDeal) GetSecShare() *SecShare {
	if x != nil {
		return x.SecShare
	}
	return nil
}

func (x *PlainDeal) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *PlainDeal) GetCommitments() []*Point {
	if x != nil {
		return x.Commitments
	}
	return nil
}

type SecShare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	I             uint32                 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
	V             *Scalar                `protobuf:"bytes,2,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecShare) Reset() {
	*x = SecShare{}
	mi := &file_deal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecShare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecShare) ProtoMessage() {}

func (x *SecShare) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecShare.ProtoReflect.Descriptor instead.
func (*SecShare) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{7}
}

func (x *SecShare) GetI() uint32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *SecShare) GetV() *Scalar {
	if x != nil {
		return x.V
	}
	return nil
}

type Scalar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scalar) Reset() {
	*x = Scalar{}
	mi := &file_deal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scalar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scalar) ProtoMessage() {}

func (x *Scalar) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scalar.ProtoReflect.Descriptor instead.
func (*Scalar) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{8}
}

func (x *Scalar) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_deal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_deal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_deal_proto_rawDescGZIP(), []int{9}
}

func (x *Point) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_deal_proto protoreflect.FileDescriptor

var file_deal_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x64, 0x65, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x64, 0x6b, 0x67, 0x2e, 0x76, 0x30, 0x22, 0x73, 0x0a, 0x0d, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x64, 0x68, 0x5f,
	0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x22,
	0x95, 0x01, 0x0a, 0x04, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x28,
	0x0a, 0x0f, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2f, 0x0a, 0x04, 0x64, 0x65, 0x61, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x64,
	0x6b, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x44,
	0x65, 0x61, 0x6c, 0x52, 0x04, 0x64, 0x65, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x5f, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x3d, 0x0a, 0x0c, 0x76, 0x73, 0x73,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x64, 0x6b, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x56,
	0x53, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x76, 0x73, 0x73, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x79, 0x0a, 0x0b, 0x56, 0x53, 0x53, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x22, 0x73, 0x0a, 0x0d, 0x4a, 0x75, 0x73, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x4c, 0x0a, 0x11, 0x76, 0x73,
	0x73, 0x5f, 0x6a, 0x75, 0x73, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x64, 0x6b,
	0x67, 0x2e, 0x76, 0x30, 0x2e, 0x56, 0x53, 0x53, 0x4a, 0x75, 0x73, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x76, 0x73, 0x73, 0x5f, 0x6a, 0x75, 0x73, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9f, 0x01, 0x0a, 0x10, 0x56, 0x53, 0x53,
	0x4a, 0x75, 0x73, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x37, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x65, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e,
	0x64, 0x6b, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x44, 0x65, 0x61, 0x6c,
	0x52, 0x0a, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x65, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0xb6, 0x01, 0x0a, 0x09, 0x50,
	0x6c, 0x61, 0x69, 0x6e, 0x44, 0x65, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x12, 0x34, 0x0a, 0x09, 0x73, 0x65, 0x63, 0x5f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x2e, 0x64, 0x6b, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x65, 0x63, 0x53, 0x68,
	0x61, 0x72, 0x65, 0x52, 0x09, 0x73, 0x65, 0x63, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x12, 0x35, 0x0a, 0x0b,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x64, 0x6b, 0x67, 0x2e, 0x76, 0x30,
	0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x22, 0x3c, 0x0a, 0x08, 0x53, 0x65, 0x63, 0x53, 0x68, 0x61, 0x72, 0x65, 0x12,
	0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x69, 0x12, 0x22, 0x0a,
	0x01, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x64, 0x6b, 0x67, 0x2e, 0x76, 0x30, 0x2e, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x52, 0x01,
	0x76, 0x22, 0x1c, 0x0a, 0x06, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x1b, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x2d, 0x5a, 0x2b,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x70, 0x6c, 0x61,
	0x62, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x2d, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_deal_proto_rawDescOnce sync.Once
	file_deal_proto_rawDescData []byte
)

func file_deal_proto_rawDescGZIP() []byte {
	file_deal_proto_rawDescOnce.Do(func() {
		file_deal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deal_proto_rawDesc), len(file_deal_proto_rawDesc)))
	})
	return file_deal_proto_rawDescData
}

var file_deal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_deal_proto_goTypes = []any{
	(*EncryptedDeal)(nil),    // 0: story.dkg.v0.EncryptedDeal
	(*Deal)(nil),             // 1: story.dkg.v0.Deal
	(*Response)(nil),         // 2: story.dkg.v0.Response
	(*VSSResponse)(nil),      // 3: story.dkg.v0.VSSResponse
	(*Justification)(nil),    // 4: story.dkg.v0.Justification
	(*VSSJustification)(nil), // 5: story.dkg.v0.VSSJustification
	(*PlainDeal)(nil),        // 6: story.dkg.v0.PlainDeal
	(*SecShare)(nil),         // 7: story.dkg.v0.SecShare
	(*Scalar)(nil),           // 8: story.dkg.v0.Scalar
	(*Point)(nil),            // 9: story.dkg.v0.Point
}
var file_deal_proto_depIdxs = []int32{
	0, // 0: story.dkg.v0.Deal.deal:type_name -> story.dkg.v0.EncryptedDeal
	3, // 1: story.dkg.v0.Response.vss_response:type_name -> story.dkg.v0.VSSResponse
	5, // 2: story.dkg.v0.Justification.vss_justification:type_name -> story.dkg.v0.VSSJustification
	6, // 3: story.dkg.v0.VSSJustification.plain_deal:type_name -> story.dkg.v0.PlainDeal
	7, // 4: story.dkg.v0.PlainDeal.sec_share:type_name -> story.dkg.v0.SecShare
	9, // 5: story.dkg.v0.PlainDeal.commitments:type_name -> story.dkg.v0.Point
	8, // 6: story.dkg.v0.SecShare.v:type_name -> story.dkg.v0.Scalar
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_deal_proto_init() }
func file_deal_proto_init() {
	if File_deal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deal_proto_rawDesc), len(file_deal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deal_proto_goTypes,
		DependencyIndexes: file_deal_proto_depIdxs,
		MessageInfos:      file_deal_proto_msgTypes,
	}.Build()
	File_deal_proto = out.File
	file_deal_proto_goTypes = nil
	file_deal_proto_depIdxs = nil
}
