// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: tee.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DKGStage int32

const (
	DKGStage_DKG_STAGE_UNSPECIFIED  DKGStage = 0
	DKGStage_DKG_STAGE_REGISTRATION DKGStage = 1
	DKGStage_DKG_STAGE_DEALING      DKGStage = 2
	DKGStage_DKG_STAGE_FINALIZATION DKGStage = 3
	DKGStage_DKG_STAGE_ACTIVE       DKGStage = 4
	DKGStage_DKG_STAGE_FAILED       DKGStage = 5
)

// Enum value maps for DKGStage.
var (
	DKGStage_name = map[int32]string{
		0: "DKG_STAGE_UNSPECIFIED",
		1: "DKG_STAGE_REGISTRATION",
		2: "DKG_STAGE_DEALING",
		3: "DKG_STAGE_FINALIZATION",
		4: "DKG_STAGE_ACTIVE",
		5: "DKG_STAGE_FAILED",
	}
	DKGStage_value = map[string]int32{
		"DKG_STAGE_UNSPECIFIED":  0,
		"DKG_STAGE_REGISTRATION": 1,
		"DKG_STAGE_DEALING":      2,
		"DKG_STAGE_FINALIZATION": 3,
		"DKG_STAGE_ACTIVE":       4,
		"DKG_STAGE_FAILED":       5,
	}
)

func (x DKGStage) Enum() *DKGStage {
	p := new(DKGStage)
	*p = x
	return p
}

func (x DKGStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DKGStage) Descriptor() protoreflect.EnumDescriptor {
	return file_tee_proto_enumTypes[0].Descriptor()
}

func (DKGStage) Type() protoreflect.EnumType {
	return &file_tee_proto_enumTypes[0]
}

func (x DKGStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DKGStage.Descriptor instead.
func (DKGStage) EnumDescriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{0}
}

type DKGRegStatus int32

const (
	DKGRegStatus_DKG_REG_STATUS_UNSPECIFIED DKGRegStatus = 0
	DKGRegStatus_DKG_REG_STATUS_VERIFIED    DKGRegStatus = 1
	DKGRegStatus_DKG_REG_STATUS_FINALIZED   DKGRegStatus = 2
	DKGRegStatus_DKG_REG_STATUS_INVALIDATED DKGRegStatus = 3
)

// Enum value maps for DKGRegStatus.
var (
	DKGRegStatus_name = map[int32]string{
		0: "DKG_REG_STATUS_UNSPECIFIED",
		1: "DKG_REG_STATUS_VERIFIED",
		2: "DKG_REG_STATUS_FINALIZED",
		3: "DKG_REG_STATUS_INVALIDATED",
	}
	DKGRegStatus_value = map[string]int32{
		"DKG_REG_STATUS_UNSPECIFIED": 0,
		"DKG_REG_STATUS_VERIFIED":    1,
		"DKG_REG_STATUS_FINALIZED":   2,
		"DKG_REG_STATUS_INVALIDATED": 3,
	}
)

func (x DKGRegStatus) Enum() *DKGRegStatus {
	p := new(DKGRegStatus)
	*p = x
	return p
}

func (x DKGRegStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DKGRegStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tee_proto_enumTypes[1].Descriptor()
}

func (DKGRegStatus) Type() protoreflect.EnumType {
	return &file_tee_proto_enumTypes[1]
}

func (x DKGRegStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DKGRegStatus.Descriptor instead.
func (DKGRegStatus) EnumDescriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{1}
}

type GenerateAndSealKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round          uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateAndSealKeyRequest) Reset() {
	*x = GenerateAndSealKeyRequest{}
	mi := &file_tee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAndSealKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAndSealKeyRequest) ProtoMessage() {}

func (x *GenerateAndSealKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAndSealKeyRequest.ProtoReflect.Descriptor instead.
func (*GenerateAndSealKeyRequest) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateAndSealKeyRequest) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *GenerateAndSealKeyRequest) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *GenerateAndSealKeyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GenerateAndSealKeyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment   []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round            uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	StartBlockHeight int64                  `protobuf:"varint,3,opt,name=start_block_height,proto3" json:"start_block_height,omitempty"`
	StartBlockHash   []byte                 `protobuf:"bytes,4,opt,name=start_block_hash,proto3" json:"start_block_hash,omitempty"`
	DkgPubKey        []byte                 `protobuf:"bytes,5,opt,name=dkg_pub_key,proto3" json:"dkg_pub_key,omitempty"`
	CommPubKey       []byte                 `protobuf:"bytes,6,opt,name=comm_pub_key,proto3" json:"comm_pub_key,omitempty"`
	RawQuote         []byte                 `protobuf:"bytes,7,opt,name=raw_quote,proto3" json:"raw_quote,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateAndSealKeyResponse) Reset() {
	*x = GenerateAndSealKeyResponse{}
	mi := &file_tee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAndSealKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAndSealKeyResponse) ProtoMessage() {}

func (x *GenerateAndSealKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAndSealKeyResponse.ProtoReflect.Descriptor instead.
func (*GenerateAndSealKeyResponse) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateAndSealKeyResponse) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *GenerateAndSealKeyResponse) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *GenerateAndSealKeyResponse) GetStartBlockHeight() int64 {
	if x != nil {
		return x.StartBlockHeight
	}
	return 0
}

func (x *GenerateAndSealKeyResponse) GetStartBlockHash() []byte {
	if x != nil {
		return x.StartBlockHash
	}
	return nil
}

func (x *GenerateAndSealKeyResponse) GetDkgPubKey() []byte {
	if x != nil {
		return x.DkgPubKey
	}
	return nil
}

func (x *GenerateAndSealKeyResponse) GetCommPubKey() []byte {
	if x != nil {
		return x.CommPubKey
	}
	return nil
}

func (x *GenerateAndSealKeyResponse) GetRawQuote() []byte {
	if x != nil {
		return x.RawQuote
	}
	return nil
}

type DKGRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         uint32                 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	ValidatorAddr string                 `protobuf:"bytes,2,opt,name=validator_addr,proto3" json:"validator_addr,omitempty"`
	Index         uint32                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	DkgPubKey     []byte                 `protobuf:"bytes,4,opt,name=dkg_pub_key,proto3" json:"dkg_pub_key,omitempty"`
	CommPubKey    []byte                 `protobuf:"bytes,5,opt,name=comm_pub_key,proto3" json:"comm_pub_key,omitempty"`
	RawQuote      []byte                 `protobuf:"bytes,6,opt,name=raw_quote,proto3" json:"raw_quote,omitempty"`
	Status        DKGRegStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=story.dkg.v0.DKGRegStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DKGRegistration) Reset() {
	*x = DKGRegistration{}
	mi := &file_tee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DKGRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKGRegistration) ProtoMessage() {}

func (x *DKGRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKGRegistration.ProtoReflect.Descriptor instead.
func (*DKGRegistration) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{2}
}

func (x *DKGRegistration) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *DKGRegistration) GetValidatorAddr() string {
	if x != nil {
		return x.ValidatorAddr
	}
	return ""
}

func (x *DKGRegistration) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DKGRegistration) GetDkgPubKey() []byte {
	if x != nil {
		return x.DkgPubKey
	}
	return nil
}

func (x *DKGRegistration) GetCommPubKey() []byte {
	if x != nil {
		return x.CommPubKey
	}
	return nil
}

func (x *DKGRegistration) GetRawQuote() []byte {
	if x != nil {
		return x.RawQuote
	}
	return nil
}

func (x *DKGRegistration) GetStatus() DKGRegStatus {
	if x != nil {
		return x.Status
	}
	return DKGRegStatus_DKG_REG_STATUS_UNSPECIFIED
}

type DKGNetwork struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment   []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round            uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	StartBlockHeight int64                  `protobuf:"varint,3,opt,name=start_block_height,proto3" json:"start_block_height,omitempty"`
	StartBlockHash   []byte                 `protobuf:"bytes,4,opt,name=start_block_hash,proto3" json:"start_block_hash,omitempty"`
	ActiveValSet     []string               `protobuf:"bytes,5,rep,name=active_val_set,proto3" json:"active_val_set,omitempty"`
	Total            uint32                 `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	Threshold        uint32                 `protobuf:"varint,7,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Stage            DKGStage               `protobuf:"varint,8,opt,name=stage,proto3,enum=story.dkg.v0.DKGStage" json:"stage,omitempty"`
	IsResharing      bool                   `protobuf:"varint,9,opt,name=is_resharing,proto3" json:"is_resharing,omitempty"`
	GlobalPublicKey  []byte                 `protobuf:"bytes,10,opt,name=global_public_key,proto3" json:"global_public_key,omitempty"`
	PublicCoeffs     [][]byte               `protobuf:"bytes,11,rep,name=public_coeffs,proto3" json:"public_coeffs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DKGNetwork) Reset() {
	*x = DKGNetwork{}
	mi := &file_tee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DKGNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DKGNetwork) ProtoMessage() {}

func (x *DKGNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DKGNetwork.ProtoReflect.Descriptor instead.
func (*DKGNetwork) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{3}
}

func (x *DKGNetwork) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *DKGNetwork) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *DKGNetwork) GetStartBlockHeight() int64 {
	if x != nil {
		return x.StartBlockHeight
	}
	return 0
}

func (x *DKGNetwork) GetStartBlockHash() []byte {
	if x != nil {
		return x.StartBlockHash
	}
	return nil
}

func (x *DKGNetwork) GetActiveValSet() []string {
	if x != nil {
		return x.ActiveValSet
	}
	return nil
}

func (x *DKGNetwork) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DKGNetwork) GetThreshold() uint32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *DKGNetwork) GetStage() DKGStage {
	if x != nil {
		return x.Stage
	}
	return DKGStage_DKG_STAGE_UNSPECIFIED
}

func (x *DKGNetwork) GetIsResharing() bool {
	if x != nil {
		return x.IsResharing
	}
	return false
}

func (x *DKGNetwork) GetGlobalPublicKey() []byte {
	if x != nil {
		return x.GlobalPublicKey
	}
	return nil
}

func (x *DKGNetwork) GetPublicCoeffs() [][]byte {
	if x != nil {
		return x.PublicCoeffs
	}
	return nil
}

type GenerateDealsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round          uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	IsResharing    bool                   `protobuf:"varint,3,opt,name=is_resharing,proto3" json:"is_resharing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateDealsRequest) Reset() {
	*x = GenerateDealsRequest{}
	mi := &file_tee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDealsRequest) ProtoMessage() {}

func (x *GenerateDealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDealsRequest.ProtoReflect.Descriptor instead.
func (*GenerateDealsRequest) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateDealsRequest) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *GenerateDealsRequest) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *GenerateDealsRequest) GetIsResharing() bool {
	if x != nil {
		return x.IsResharing
	}
	return false
}

type GenerateDealsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round          uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Deals          []*Deal                `protobuf:"bytes,3,rep,name=deals,proto3" json:"deals,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateDealsResponse) Reset() {
	*x = GenerateDealsResponse{}
	mi := &file_tee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDealsResponse) ProtoMessage() {}

func (x *GenerateDealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDealsResponse.ProtoReflect.Descriptor instead.
func (*GenerateDealsResponse) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateDealsResponse) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *GenerateDealsResponse) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *GenerateDealsResponse) GetDeals() []*Deal {
	if x != nil {
		return x.Deals
	}
	return nil
}

type ProcessDealsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round          uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Deals          []*Deal                `protobuf:"bytes,3,rep,name=deals,proto3" json:"deals,omitempty"`
	IsResharing    bool                   `protobuf:"varint,4,opt,name=is_resharing,proto3" json:"is_resharing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessDealsRequest) Reset() {
	*x = ProcessDealsRequest{}
	mi := &file_tee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDealsRequest) ProtoMessage() {}

func (x *ProcessDealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDealsRequest.ProtoReflect.Descriptor instead.
func (*ProcessDealsRequest) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessDealsRequest) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *ProcessDealsRequest) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ProcessDealsRequest) GetDeals() []*Deal {
	if x != nil {
		return x.Deals
	}
	return nil
}

func (x *ProcessDealsRequest) GetIsResharing() bool {
	if x != nil {
		return x.IsResharing
	}
	return false
}

type ProcessDealsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round          uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Responses      []*Response            `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessDealsResponse) Reset() {
	*x = ProcessDealsResponse{}
	mi := &file_tee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDealsResponse) ProtoMessage() {}

func (x *ProcessDealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDealsResponse.ProtoReflect.Descriptor instead.
func (*ProcessDealsResponse) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessDealsResponse) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *ProcessDealsResponse) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ProcessDealsResponse) GetResponses() []*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

type ProcessResponsesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round          uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Responses      []*Response            `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`
	IsResharing    bool                   `protobuf:"varint,4,opt,name=is_resharing,proto3" json:"is_resharing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessResponsesRequest) Reset() {
	*x = ProcessResponsesRequest{}
	mi := &file_tee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponsesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponsesRequest) ProtoMessage() {}

func (x *ProcessResponsesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponsesRequest.ProtoReflect.Descriptor instead.
func (*ProcessResponsesRequest) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessResponsesRequest) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *ProcessResponsesRequest) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ProcessResponsesRequest) GetResponses() []*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *ProcessResponsesRequest) GetIsResharing() bool {
	if x != nil {
		return x.IsResharing
	}
	return false
}

type ProcessResponsesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Justifications []*Justification       `protobuf:"bytes,1,rep,name=justifications,proto3" json:"justifications,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessResponsesResponse) Reset() {
	*x = ProcessResponsesResponse{}
	mi := &file_tee_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponsesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponsesResponse) ProtoMessage() {}

func (x *ProcessResponsesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponsesResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponsesResponse) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessResponsesResponse) GetJustifications() []*Justification {
	if x != nil {
		return x.Justifications
	}
	return nil
}

// ProcessJustificationRequest is sent to TEE to process valid justifications
// and restore the DKG state by accepting the originally-complained deals.
type ProcessJustificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round          uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Justifications []*Justification       `protobuf:"bytes,3,rep,name=justifications,proto3" json:"justifications,omitempty"`
	IsResharing    bool                   `protobuf:"varint,4,opt,name=is_resharing,proto3" json:"is_resharing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessJustificationRequest) Reset() {
	*x = ProcessJustificationRequest{}
	mi := &file_tee_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessJustificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessJustificationRequest) ProtoMessage() {}

func (x *ProcessJustificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessJustificationRequest.ProtoReflect.Descriptor instead.
func (*ProcessJustificationRequest) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessJustificationRequest) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *ProcessJustificationRequest) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *ProcessJustificationRequest) GetJustifications() []*Justification {
	if x != nil {
		return x.Justifications
	}
	return nil
}

func (x *ProcessJustificationRequest) GetIsResharing() bool {
	if x != nil {
		return x.IsResharing
	}
	return false
}

// ProcessJustificationResponse is returned from TEE after processing justifications.
type ProcessJustificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessJustificationResponse) Reset() {
	*x = ProcessJustificationResponse{}
	mi := &file_tee_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessJustificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessJustificationResponse) ProtoMessage() {}

func (x *ProcessJustificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessJustificationResponse.ProtoReflect.Descriptor instead.
func (*ProcessJustificationResponse) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{11}
}

type FinalizeDKGRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round          uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	IsResharing    bool                   `protobuf:"varint,3,opt,name=is_resharing,proto3" json:"is_resharing,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinalizeDKGRequest) Reset() {
	*x = FinalizeDKGRequest{}
	mi := &file_tee_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeDKGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeDKGRequest) ProtoMessage() {}

func (x *FinalizeDKGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeDKGRequest.ProtoReflect.Descriptor instead.
func (*FinalizeDKGRequest) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{12}
}

func (x *FinalizeDKGRequest) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *FinalizeDKGRequest) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *FinalizeDKGRequest) GetIsResharing() bool {
	if x != nil {
		return x.IsResharing
	}
	return false
}

type FinalizeDKGResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment   []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round            uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	ParticipantsRoot []byte                 `protobuf:"bytes,3,opt,name=participants_root,proto3" json:"participants_root,omitempty"`
	GlobalPubKey     []byte                 `protobuf:"bytes,4,opt,name=global_pub_key,proto3" json:"global_pub_key,omitempty"`
	PublicCoeffs     [][]byte               `protobuf:"bytes,5,rep,name=public_coeffs,proto3" json:"public_coeffs,omitempty"`
	PubKeyShare      []byte                 `protobuf:"bytes,6,opt,name=pub_key_share,proto3" json:"pub_key_share,omitempty"`
	Signature        []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FinalizeDKGResponse) Reset() {
	*x = FinalizeDKGResponse{}
	mi := &file_tee_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeDKGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeDKGResponse) ProtoMessage() {}

func (x *FinalizeDKGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeDKGResponse.ProtoReflect.Descriptor instead.
func (*FinalizeDKGResponse) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{13}
}

func (x *FinalizeDKGResponse) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *FinalizeDKGResponse) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *FinalizeDKGResponse) GetParticipantsRoot() []byte {
	if x != nil {
		return x.ParticipantsRoot
	}
	return nil
}

func (x *FinalizeDKGResponse) GetGlobalPubKey() []byte {
	if x != nil {
		return x.GlobalPubKey
	}
	return nil
}

func (x *FinalizeDKGResponse) GetPublicCoeffs() [][]byte {
	if x != nil {
		return x.PublicCoeffs
	}
	return nil
}

func (x *FinalizeDKGResponse) GetPubKeyShare() []byte {
	if x != nil {
		return x.PubKeyShare
	}
	return nil
}

func (x *FinalizeDKGResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PartialDecryptTDH2Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CodeCommitment  []byte                 `protobuf:"bytes,1,opt,name=code_commitment,proto3" json:"code_commitment,omitempty"`
	Round           uint32                 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Ciphertext      []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Label           []byte                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	GlobalPubKey    []byte                 `protobuf:"bytes,5,opt,name=global_pub_key,proto3" json:"global_pub_key,omitempty"`
	SealedShareId   string                 `protobuf:"bytes,6,opt,name=sealed_share_id,proto3" json:"sealed_share_id,omitempty"`
	RequesterPubKey []byte                 `protobuf:"bytes,7,opt,name=requester_pub_key,proto3" json:"requester_pub_key,omitempty"` // secp256k1 uncompressed
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartialDecryptTDH2Request) Reset() {
	*x = PartialDecryptTDH2Request{}
	mi := &file_tee_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialDecryptTDH2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialDecryptTDH2Request) ProtoMessage() {}

func (x *PartialDecryptTDH2Request) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialDecryptTDH2Request.ProtoReflect.Descriptor instead.
func (*PartialDecryptTDH2Request) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{14}
}

func (x *PartialDecryptTDH2Request) GetCodeCommitment() []byte {
	if x != nil {
		return x.CodeCommitment
	}
	return nil
}

func (x *PartialDecryptTDH2Request) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *PartialDecryptTDH2Request) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *PartialDecryptTDH2Request) GetLabel() []byte {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *PartialDecryptTDH2Request) GetGlobalPubKey() []byte {
	if x != nil {
		return x.GlobalPubKey
	}
	return nil
}

func (x *PartialDecryptTDH2Request) GetSealedShareId() string {
	if x != nil {
		return x.SealedShareId
	}
	return ""
}

func (x *PartialDecryptTDH2Request) GetRequesterPubKey() []byte {
	if x != nil {
		return x.RequesterPubKey
	}
	return nil
}

type PartialDecryptTDH2Response struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	EncryptedPartialDecryption []byte                 `protobuf:"bytes,1,opt,name=encrypted_partial_decryption,proto3" json:"encrypted_partial_decryption,omitempty"`
	EphemeralPubKey            []byte                 `protobuf:"bytes,2,opt,name=ephemeral_pub_key,proto3" json:"ephemeral_pub_key,omitempty"`
	PubShare                   []byte                 `protobuf:"bytes,3,opt,name=pub_share,proto3" json:"pub_share,omitempty"`
	Signature                  []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PartialDecryptTDH2Response) Reset() {
	*x = PartialDecryptTDH2Response{}
	mi := &file_tee_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialDecryptTDH2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialDecryptTDH2Response) ProtoMessage() {}

func (x *PartialDecryptTDH2Response) ProtoReflect() protoreflect.Message {
	mi := &file_tee_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialDecryptTDH2Response.ProtoReflect.Descriptor instead.
func (*PartialDecryptTDH2Response) Descriptor() ([]byte, []int) {
	return file_tee_proto_rawDescGZIP(), []int{15}
}

func (x *PartialDecryptTDH2Response) GetEncryptedPartialDecryption() []byte {
	if x != nil {
		return x.EncryptedPartialDecryption
	}
	return nil
}

func (x *PartialDecryptTDH2Response) GetEphemeralPubKey() []byte {
	if x != nil {
		return x.EphemeralPubKey
	}
	return nil
}

func (x *PartialDecryptTDH2Response) GetPubShare() []byte {
	if x != nil {
		return x.PubShare
	}
	return nil
}

func (x *PartialDecryptTDH2Response) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_tee_proto protoreflect.FileDescriptor

const file_tee_proto_rawDesc = "" +
	"\n" +
	"\ttee.proto\x12\fstory.dkg.v0\x1a\n" +
	"deal.proto\"u\n" +
	"\x19GenerateAndSealKeyRequest\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x9c\x02\n" +
	"\x1aGenerateAndSealKeyResponse\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12.\n" +
	"\x12start_block_height\x18\x03 \x01(\x03R\x12start_block_height\x12*\n" +
	"\x10start_block_hash\x18\x04 \x01(\fR\x10start_block_hash\x12 \n" +
	"\vdkg_pub_key\x18\x05 \x01(\fR\vdkg_pub_key\x12\"\n" +
	"\fcomm_pub_key\x18\x06 \x01(\fR\fcomm_pub_key\x12\x1c\n" +
	"\traw_quote\x18\a \x01(\fR\traw_quote\"\xfd\x01\n" +
	"\x0fDKGRegistration\x12\x14\n" +
	"\x05round\x18\x01 \x01(\rR\x05round\x12&\n" +
	"\x0evalidator_addr\x18\x02 \x01(\tR\x0evalidator_addr\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\x12 \n" +
	"\vdkg_pub_key\x18\x04 \x01(\fR\vdkg_pub_key\x12\"\n" +
	"\fcomm_pub_key\x18\x05 \x01(\fR\fcomm_pub_key\x12\x1c\n" +
	"\traw_quote\x18\x06 \x01(\fR\traw_quote\x122\n" +
	"\x06status\x18\a \x01(\x0e2\x1a.story.dkg.v0.DKGRegStatusR\x06status\"\xaa\x03\n" +
	"\n" +
	"DKGNetwork\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12.\n" +
	"\x12start_block_height\x18\x03 \x01(\x03R\x12start_block_height\x12*\n" +
	"\x10start_block_hash\x18\x04 \x01(\fR\x10start_block_hash\x12&\n" +
	"\x0eactive_val_set\x18\x05 \x03(\tR\x0eactive_val_set\x12\x14\n" +
	"\x05total\x18\x06 \x01(\rR\x05total\x12\x1c\n" +
	"\tthreshold\x18\a \x01(\rR\tthreshold\x12,\n" +
	"\x05stage\x18\b \x01(\x0e2\x16.story.dkg.v0.DKGStageR\x05stage\x12\"\n" +
	"\fis_resharing\x18\t \x01(\bR\fis_resharing\x12,\n" +
	"\x11global_public_key\x18\n" +
	" \x01(\fR\x11global_public_key\x12$\n" +
	"\rpublic_coeffs\x18\v \x03(\fR\rpublic_coeffs\"z\n" +
	"\x14GenerateDealsRequest\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12\"\n" +
	"\fis_resharing\x18\x03 \x01(\bR\fis_resharing\"\x81\x01\n" +
	"\x15GenerateDealsResponse\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12(\n" +
	"\x05deals\x18\x03 \x03(\v2\x12.story.dkg.v0.DealR\x05deals\"\xa3\x01\n" +
	"\x13ProcessDealsRequest\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12(\n" +
	"\x05deals\x18\x03 \x03(\v2\x12.story.dkg.v0.DealR\x05deals\x12\"\n" +
	"\fis_resharing\x18\x04 \x01(\bR\fis_resharing\"\x8c\x01\n" +
	"\x14ProcessDealsResponse\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x124\n" +
	"\tresponses\x18\x03 \x03(\v2\x16.story.dkg.v0.ResponseR\tresponses\"\xb3\x01\n" +
	"\x17ProcessResponsesRequest\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x124\n" +
	"\tresponses\x18\x03 \x03(\v2\x16.story.dkg.v0.ResponseR\tresponses\x12\"\n" +
	"\fis_resharing\x18\x04 \x01(\bR\fis_resharing\"_\n" +
	"\x18ProcessResponsesResponse\x12C\n" +
	"\x0ejustifications\x18\x01 \x03(\v2\x1b.story.dkg.v0.JustificationR\x0ejustifications\"\xc6\x01\n" +
	"\x1bProcessJustificationRequest\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12C\n" +
	"\x0ejustifications\x18\x03 \x03(\v2\x1b.story.dkg.v0.JustificationR\x0ejustifications\x12\"\n" +
	"\fis_resharing\x18\x04 \x01(\bR\fis_resharing\"\x1e\n" +
	"\x1cProcessJustificationResponse\"x\n" +
	"\x12FinalizeDKGRequest\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12\"\n" +
	"\fis_resharing\x18\x03 \x01(\bR\fis_resharing\"\x95\x02\n" +
	"\x13FinalizeDKGResponse\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12,\n" +
	"\x11participants_root\x18\x03 \x01(\fR\x11participants_root\x12&\n" +
	"\x0eglobal_pub_key\x18\x04 \x01(\fR\x0eglobal_pub_key\x12$\n" +
	"\rpublic_coeffs\x18\x05 \x03(\fR\rpublic_coeffs\x12$\n" +
	"\rpub_key_share\x18\x06 \x01(\fR\rpub_key_share\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"\x91\x02\n" +
	"\x19PartialDecryptTDH2Request\x12(\n" +
	"\x0fcode_commitment\x18\x01 \x01(\fR\x0fcode_commitment\x12\x14\n" +
	"\x05round\x18\x02 \x01(\rR\x05round\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fR\n" +
	"ciphertext\x12\x14\n" +
	"\x05label\x18\x04 \x01(\fR\x05label\x12&\n" +
	"\x0eglobal_pub_key\x18\x05 \x01(\fR\x0eglobal_pub_key\x12(\n" +
	"\x0fsealed_share_id\x18\x06 \x01(\tR\x0fsealed_share_id\x12,\n" +
	"\x11requester_pub_key\x18\a \x01(\fR\x11requester_pub_key\"\xca\x01\n" +
	"\x1aPartialDecryptTDH2Response\x12B\n" +
	"\x1cencrypted_partial_decryption\x18\x01 \x01(\fR\x1cencrypted_partial_decryption\x12,\n" +
	"\x11ephemeral_pub_key\x18\x02 \x01(\fR\x11ephemeral_pub_key\x12\x1c\n" +
	"\tpub_share\x18\x03 \x01(\fR\tpub_share\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature*\xa0\x01\n" +
	"\bDKGStage\x12\x19\n" +
	"\x15DKG_STAGE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DKG_STAGE_REGISTRATION\x10\x01\x12\x15\n" +
	"\x11DKG_STAGE_DEALING\x10\x02\x12\x1a\n" +
	"\x16DKG_STAGE_FINALIZATION\x10\x03\x12\x14\n" +
	"\x10DKG_STAGE_ACTIVE\x10\x04\x12\x14\n" +
	"\x10DKG_STAGE_FAILED\x10\x05*\x89\x01\n" +
	"\fDKGRegStatus\x12\x1e\n" +
	"\x1aDKG_REG_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DKG_REG_STATUS_VERIFIED\x10\x01\x12\x1c\n" +
	"\x18DKG_REG_STATUS_FINALIZED\x10\x02\x12\x1e\n" +
	"\x1aDKG_REG_STATUS_INVALIDATED\x10\x032\xb5\x05\n" +
	"\n" +
	"TEEService\x12g\n" +
	"\x12GenerateAndSealKey\x12'.story.dkg.v0.GenerateAndSealKeyRequest\x1a(.story.dkg.v0.GenerateAndSealKeyResponse\x12X\n" +
	"\rGenerateDeals\x12\".story.dkg.v0.GenerateDealsRequest\x1a#.story.dkg.v0.GenerateDealsResponse\x12U\n" +
	"\fProcessDeals\x12!.story.dkg.v0.ProcessDealsRequest\x1a\".story.dkg.v0.ProcessDealsResponse\x12a\n" +
	"\x10ProcessResponses\x12%.story.dkg.v0.ProcessResponsesRequest\x1a&.story.dkg.v0.ProcessResponsesResponse\x12m\n" +
	"\x14ProcessJustification\x12).story.dkg.v0.ProcessJustificationRequest\x1a*.story.dkg.v0.ProcessJustificationResponse\x12R\n" +
	"\vFinalizeDKG\x12 .story.dkg.v0.FinalizeDKGRequest\x1a!.story.dkg.v0.FinalizeDKGResponse\x12g\n" +
	"\x12PartialDecryptTDH2\x12'.story.dkg.v0.PartialDecryptTDH2Request\x1a(.story.dkg.v0.PartialDecryptTDH2ResponseB-Z+github.com/piplabs/story-kernel/types/pb/v0b\x06proto3"

var (
	file_tee_proto_rawDescOnce sync.Once
	file_tee_proto_rawDescData []byte
)

func file_tee_proto_rawDescGZIP() []byte {
	file_tee_proto_rawDescOnce.Do(func() {
		file_tee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tee_proto_rawDesc), len(file_tee_proto_rawDesc)))
	})
	return file_tee_proto_rawDescData
}

var file_tee_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tee_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_tee_proto_goTypes = []any{
	(DKGStage)(0),                        // 0: story.dkg.v0.DKGStage
	(DKGRegStatus)(0),                    // 1: story.dkg.v0.DKGRegStatus
	(*GenerateAndSealKeyRequest)(nil),    // 2: story.dkg.v0.GenerateAndSealKeyRequest
	(*GenerateAndSealKeyResponse)(nil),   // 3: story.dkg.v0.GenerateAndSealKeyResponse
	(*DKGRegistration)(nil),              // 4: story.dkg.v0.DKGRegistration
	(*DKGNetwork)(nil),                   // 5: story.dkg.v0.DKGNetwork
	(*GenerateDealsRequest)(nil),         // 6: story.dkg.v0.GenerateDealsRequest
	(*GenerateDealsResponse)(nil),        // 7: story.dkg.v0.GenerateDealsResponse
	(*ProcessDealsRequest)(nil),          // 8: story.dkg.v0.ProcessDealsRequest
	(*ProcessDealsResponse)(nil),         // 9: story.dkg.v0.ProcessDealsResponse
	(*ProcessResponsesRequest)(nil),      // 10: story.dkg.v0.ProcessResponsesRequest
	(*ProcessResponsesResponse)(nil),     // 11: story.dkg.v0.ProcessResponsesResponse
	(*ProcessJustificationRequest)(nil),  // 12: story.dkg.v0.ProcessJustificationRequest
	(*ProcessJustificationResponse)(nil), // 13: story.dkg.v0.ProcessJustificationResponse
	(*FinalizeDKGRequest)(nil),           // 14: story.dkg.v0.FinalizeDKGRequest
	(*FinalizeDKGResponse)(nil),          // 15: story.dkg.v0.FinalizeDKGResponse
	(*PartialDecryptTDH2Request)(nil),    // 16: story.dkg.v0.PartialDecryptTDH2Request
	(*PartialDecryptTDH2Response)(nil),   // 17: story.dkg.v0.PartialDecryptTDH2Response
	(*Deal)(nil),                         // 18: story.dkg.v0.Deal
	(*Response)(nil),                     // 19: story.dkg.v0.Response
	(*Justification)(nil),                // 20: story.dkg.v0.Justification
}
var file_tee_proto_depIdxs = []int32{
	1,  // 0: story.dkg.v0.DKGRegistration.status:type_name -> story.dkg.v0.DKGRegStatus
	0,  // 1: story.dkg.v0.DKGNetwork.stage:type_name -> story.dkg.v0.DKGStage
	18, // 2: story.dkg.v0.GenerateDealsResponse.deals:type_name -> story.dkg.v0.Deal
	18, // 3: story.dkg.v0.ProcessDealsRequest.deals:type_name -> story.dkg.v0.Deal
	19, // 4: story.dkg.v0.ProcessDealsResponse.responses:type_name -> story.dkg.v0.Response
	19, // 5: story.dkg.v0.ProcessResponsesRequest.responses:type_name -> story.dkg.v0.Response
	20, // 6: story.dkg.v0.ProcessResponsesResponse.justifications:type_name -> story.dkg.v0.Justification
	20, // 7: story.dkg.v0.ProcessJustificationRequest.justifications:type_name -> story.dkg.v0.Justification
	2,  // 8: story.dkg.v0.TEEService.GenerateAndSealKey:input_type -> story.dkg.v0.GenerateAndSealKeyRequest
	6,  // 9: story.dkg.v0.TEEService.GenerateDeals:input_type -> story.dkg.v0.GenerateDealsRequest
	8,  // 10: story.dkg.v0.TEEService.ProcessDeals:input_type -> story.dkg.v0.ProcessDealsRequest
	10, // 11: story.dkg.v0.TEEService.ProcessResponses:input_type -> story.dkg.v0.ProcessResponsesRequest
	12, // 12: story.dkg.v0.TEEService.ProcessJustification:input_type -> story.dkg.v0.ProcessJustificationRequest
	14, // 13: story.dkg.v0.TEEService.FinalizeDKG:input_type -> story.dkg.v0.FinalizeDKGRequest
	16, // 14: story.dkg.v0.TEEService.PartialDecryptTDH2:input_type -> story.dkg.v0.PartialDecryptTDH2Request
	3,  // 15: story.dkg.v0.TEEService.GenerateAndSealKey:output_type -> story.dkg.v0.GenerateAndSealKeyResponse
	7,  // 16: story.dkg.v0.TEEService.GenerateDeals:output_type -> story.dkg.v0.GenerateDealsResponse
	9,  // 17: story.dkg.v0.TEEService.ProcessDeals:output_type -> story.dkg.v0.ProcessDealsResponse
	11, // 18: story.dkg.v0.TEEService.ProcessResponses:output_type -> story.dkg.v0.ProcessResponsesResponse
	13, // 19: story.dkg.v0.TEEService.ProcessJustification:output_type -> story.dkg.v0.ProcessJustificationResponse
	15, // 20: story.dkg.v0.TEEService.FinalizeDKG:output_type -> story.dkg.v0.FinalizeDKGResponse
	17, // 21: story.dkg.v0.TEEService.PartialDecryptTDH2:output_type -> story.dkg.v0.PartialDecryptTDH2Response
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_tee_proto_init() }
func file_tee_proto_init() {
	if File_tee_proto != nil {
		return
	}
	file_deal_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tee_proto_rawDesc), len(file_tee_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tee_proto_goTypes,
		DependencyIndexes: file_tee_proto_depIdxs,
		EnumInfos:         file_tee_proto_enumTypes,
		MessageInfos:      file_tee_proto_msgTypes,
	}.Build()
	File_tee_proto = out.File
	file_tee_proto_goTypes = nil
	file_tee_proto_depIdxs = nil
}
