// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: tee.proto

package v0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TEEService_GenerateAndSealKey_FullMethodName = "/story.dkg.v0.TEEService/GenerateAndSealKey"
	TEEService_GenerateDeals_FullMethodName      = "/story.dkg.v0.TEEService/GenerateDeals"
	TEEService_ProcessDeals_FullMethodName       = "/story.dkg.v0.TEEService/ProcessDeals"
	TEEService_ProcessResponses_FullMethodName   = "/story.dkg.v0.TEEService/ProcessResponses"
	TEEService_FinalizeDKG_FullMethodName        = "/story.dkg.v0.TEEService/FinalizeDKG"
	TEEService_PartialDecryptTDH2_FullMethodName = "/story.dkg.v0.TEEService/PartialDecryptTDH2"
)

// TEEServiceClient is the client API for TEEService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TEEServiceClient interface {
	GenerateAndSealKey(ctx context.Context, in *GenerateAndSealKeyRequest, opts ...grpc.CallOption) (*GenerateAndSealKeyResponse, error)
	GenerateDeals(ctx context.Context, in *GenerateDealsRequest, opts ...grpc.CallOption) (*GenerateDealsResponse, error)
	ProcessDeals(ctx context.Context, in *ProcessDealsRequest, opts ...grpc.CallOption) (*ProcessDealsResponse, error)
	ProcessResponses(ctx context.Context, in *ProcessResponsesRequest, opts ...grpc.CallOption) (*ProcessResponsesResponse, error)
	FinalizeDKG(ctx context.Context, in *FinalizeDKGRequest, opts ...grpc.CallOption) (*FinalizeDKGResponse, error)
	PartialDecryptTDH2(ctx context.Context, in *PartialDecryptTDH2Request, opts ...grpc.CallOption) (*PartialDecryptTDH2Response, error)
}

type tEEServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTEEServiceClient(cc grpc.ClientConnInterface) TEEServiceClient {
	return &tEEServiceClient{cc}
}

func (c *tEEServiceClient) GenerateAndSealKey(ctx context.Context, in *GenerateAndSealKeyRequest, opts ...grpc.CallOption) (*GenerateAndSealKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAndSealKeyResponse)
	err := c.cc.Invoke(ctx, TEEService_GenerateAndSealKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEServiceClient) GenerateDeals(ctx context.Context, in *GenerateDealsRequest, opts ...grpc.CallOption) (*GenerateDealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDealsResponse)
	err := c.cc.Invoke(ctx, TEEService_GenerateDeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEServiceClient) ProcessDeals(ctx context.Context, in *ProcessDealsRequest, opts ...grpc.CallOption) (*ProcessDealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDealsResponse)
	err := c.cc.Invoke(ctx, TEEService_ProcessDeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEServiceClient) ProcessResponses(ctx context.Context, in *ProcessResponsesRequest, opts ...grpc.CallOption) (*ProcessResponsesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponsesResponse)
	err := c.cc.Invoke(ctx, TEEService_ProcessResponses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEServiceClient) FinalizeDKG(ctx context.Context, in *FinalizeDKGRequest, opts ...grpc.CallOption) (*FinalizeDKGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeDKGResponse)
	err := c.cc.Invoke(ctx, TEEService_FinalizeDKG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tEEServiceClient) PartialDecryptTDH2(ctx context.Context, in *PartialDecryptTDH2Request, opts ...grpc.CallOption) (*PartialDecryptTDH2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartialDecryptTDH2Response)
	err := c.cc.Invoke(ctx, TEEService_PartialDecryptTDH2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TEEServiceServer is the server API for TEEService service.
// All implementations must embed UnimplementedTEEServiceServer
// for forward compatibility.
type TEEServiceServer interface {
	GenerateAndSealKey(context.Context, *GenerateAndSealKeyRequest) (*GenerateAndSealKeyResponse, error)
	GenerateDeals(context.Context, *GenerateDealsRequest) (*GenerateDealsResponse, error)
	ProcessDeals(context.Context, *ProcessDealsRequest) (*ProcessDealsResponse, error)
	ProcessResponses(context.Context, *ProcessResponsesRequest) (*ProcessResponsesResponse, error)
	FinalizeDKG(context.Context, *FinalizeDKGRequest) (*FinalizeDKGResponse, error)
	PartialDecryptTDH2(context.Context, *PartialDecryptTDH2Request) (*PartialDecryptTDH2Response, error)
	mustEmbedUnimplementedTEEServiceServer()
}

// UnimplementedTEEServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTEEServiceServer struct{}

func (UnimplementedTEEServiceServer) GenerateAndSealKey(context.Context, *GenerateAndSealKeyRequest) (*GenerateAndSealKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAndSealKey not implemented")
}
func (UnimplementedTEEServiceServer) GenerateDeals(context.Context, *GenerateDealsRequest) (*GenerateDealsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDeals not implemented")
}
func (UnimplementedTEEServiceServer) ProcessDeals(context.Context, *ProcessDealsRequest) (*ProcessDealsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessDeals not implemented")
}
func (UnimplementedTEEServiceServer) ProcessResponses(context.Context, *ProcessResponsesRequest) (*ProcessResponsesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessResponses not implemented")
}
func (UnimplementedTEEServiceServer) FinalizeDKG(context.Context, *FinalizeDKGRequest) (*FinalizeDKGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeDKG not implemented")
}
func (UnimplementedTEEServiceServer) PartialDecryptTDH2(context.Context, *PartialDecryptTDH2Request) (*PartialDecryptTDH2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartialDecryptTDH2 not implemented")
}
func (UnimplementedTEEServiceServer) mustEmbedUnimplementedTEEServiceServer() {}
func (UnimplementedTEEServiceServer) testEmbeddedByValue()                    {}

// UnsafeTEEServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TEEServiceServer will
// result in compilation errors.
type UnsafeTEEServiceServer interface {
	mustEmbedUnimplementedTEEServiceServer()
}

func RegisterTEEServiceServer(s grpc.ServiceRegistrar, srv TEEServiceServer) {
	// If the following call pancis, it indicates UnimplementedTEEServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TEEService_ServiceDesc, srv)
}

func _TEEService_GenerateAndSealKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAndSealKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServiceServer).GenerateAndSealKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEEService_GenerateAndSealKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServiceServer).GenerateAndSealKey(ctx, req.(*GenerateAndSealKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEEService_GenerateDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServiceServer).GenerateDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEEService_GenerateDeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServiceServer).GenerateDeals(ctx, req.(*GenerateDealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEEService_ProcessDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessDealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServiceServer).ProcessDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEEService_ProcessDeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServiceServer).ProcessDeals(ctx, req.(*ProcessDealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEEService_ProcessResponses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessResponsesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServiceServer).ProcessResponses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEEService_ProcessResponses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServiceServer).ProcessResponses(ctx, req.(*ProcessResponsesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEEService_FinalizeDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeDKGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServiceServer).FinalizeDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEEService_FinalizeDKG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServiceServer).FinalizeDKG(ctx, req.(*FinalizeDKGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TEEService_PartialDecryptTDH2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartialDecryptTDH2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TEEServiceServer).PartialDecryptTDH2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TEEService_PartialDecryptTDH2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TEEServiceServer).PartialDecryptTDH2(ctx, req.(*PartialDecryptTDH2Request))
	}
	return interceptor(ctx, in, info, handler)
}

// TEEService_ServiceDesc is the grpc.ServiceDesc for TEEService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TEEService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "story.dkg.v0.TEEService",
	HandlerType: (*TEEServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAndSealKey",
			Handler:    _TEEService_GenerateAndSealKey_Handler,
		},
		{
			MethodName: "GenerateDeals",
			Handler:    _TEEService_GenerateDeals_Handler,
		},
		{
			MethodName: "ProcessDeals",
			Handler:    _TEEService_ProcessDeals_Handler,
		},
		{
			MethodName: "ProcessResponses",
			Handler:    _TEEService_ProcessResponses_Handler,
		},
		{
			MethodName: "FinalizeDKG",
			Handler:    _TEEService_FinalizeDKG_Handler,
		},
		{
			MethodName: "PartialDecryptTDH2",
			Handler:    _TEEService_PartialDecryptTDH2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tee.proto",
}
