// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: tee.proto

package v0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KernelService_GetCodeCommitment_FullMethodName    = "/story.dkg.v1.types.KernelService/GetCodeCommitment"
	KernelService_GenerateAndSealKey_FullMethodName   = "/story.dkg.v1.types.KernelService/GenerateAndSealKey"
	KernelService_GenerateDeals_FullMethodName        = "/story.dkg.v1.types.KernelService/GenerateDeals"
	KernelService_ProcessDeals_FullMethodName         = "/story.dkg.v1.types.KernelService/ProcessDeals"
	KernelService_ProcessResponses_FullMethodName     = "/story.dkg.v1.types.KernelService/ProcessResponses"
	KernelService_ProcessJustification_FullMethodName = "/story.dkg.v1.types.KernelService/ProcessJustification"
	KernelService_FinalizeDKG_FullMethodName          = "/story.dkg.v1.types.KernelService/FinalizeDKG"
	KernelService_PartialDecryptTDH2_FullMethodName   = "/story.dkg.v1.types.KernelService/PartialDecryptTDH2"
)

// KernelServiceClient is the client API for KernelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KernelServiceClient interface {
	GetCodeCommitment(ctx context.Context, in *GetCodeCommitmentRequest, opts ...grpc.CallOption) (*GetCodeCommitmentResponse, error)
	GenerateAndSealKey(ctx context.Context, in *GenerateAndSealKeyRequest, opts ...grpc.CallOption) (*GenerateAndSealKeyResponse, error)
	GenerateDeals(ctx context.Context, in *GenerateDealsRequest, opts ...grpc.CallOption) (*GenerateDealsResponse, error)
	ProcessDeals(ctx context.Context, in *ProcessDealsRequest, opts ...grpc.CallOption) (*ProcessDealsResponse, error)
	ProcessResponses(ctx context.Context, in *ProcessResponsesRequest, opts ...grpc.CallOption) (*ProcessResponsesResponse, error)
	ProcessJustification(ctx context.Context, in *ProcessJustificationRequest, opts ...grpc.CallOption) (*ProcessJustificationResponse, error)
	FinalizeDKG(ctx context.Context, in *FinalizeDKGRequest, opts ...grpc.CallOption) (*FinalizeDKGResponse, error)
	PartialDecryptTDH2(ctx context.Context, in *PartialDecryptTDH2Request, opts ...grpc.CallOption) (*PartialDecryptTDH2Response, error)
}

type kernelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelServiceClient(cc grpc.ClientConnInterface) KernelServiceClient {
	return &kernelServiceClient{cc}
}

func (c *kernelServiceClient) GetCodeCommitment(ctx context.Context, in *GetCodeCommitmentRequest, opts ...grpc.CallOption) (*GetCodeCommitmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCodeCommitmentResponse)
	err := c.cc.Invoke(ctx, KernelService_GetCodeCommitment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) GenerateAndSealKey(ctx context.Context, in *GenerateAndSealKeyRequest, opts ...grpc.CallOption) (*GenerateAndSealKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateAndSealKeyResponse)
	err := c.cc.Invoke(ctx, KernelService_GenerateAndSealKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) GenerateDeals(ctx context.Context, in *GenerateDealsRequest, opts ...grpc.CallOption) (*GenerateDealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDealsResponse)
	err := c.cc.Invoke(ctx, KernelService_GenerateDeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) ProcessDeals(ctx context.Context, in *ProcessDealsRequest, opts ...grpc.CallOption) (*ProcessDealsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessDealsResponse)
	err := c.cc.Invoke(ctx, KernelService_ProcessDeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) ProcessResponses(ctx context.Context, in *ProcessResponsesRequest, opts ...grpc.CallOption) (*ProcessResponsesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponsesResponse)
	err := c.cc.Invoke(ctx, KernelService_ProcessResponses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) ProcessJustification(ctx context.Context, in *ProcessJustificationRequest, opts ...grpc.CallOption) (*ProcessJustificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessJustificationResponse)
	err := c.cc.Invoke(ctx, KernelService_ProcessJustification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) FinalizeDKG(ctx context.Context, in *FinalizeDKGRequest, opts ...grpc.CallOption) (*FinalizeDKGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeDKGResponse)
	err := c.cc.Invoke(ctx, KernelService_FinalizeDKG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelServiceClient) PartialDecryptTDH2(ctx context.Context, in *PartialDecryptTDH2Request, opts ...grpc.CallOption) (*PartialDecryptTDH2Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PartialDecryptTDH2Response)
	err := c.cc.Invoke(ctx, KernelService_PartialDecryptTDH2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelServiceServer is the server API for KernelService service.
// All implementations must embed UnimplementedKernelServiceServer
// for forward compatibility.
type KernelServiceServer interface {
	GetCodeCommitment(context.Context, *GetCodeCommitmentRequest) (*GetCodeCommitmentResponse, error)
	GenerateAndSealKey(context.Context, *GenerateAndSealKeyRequest) (*GenerateAndSealKeyResponse, error)
	GenerateDeals(context.Context, *GenerateDealsRequest) (*GenerateDealsResponse, error)
	ProcessDeals(context.Context, *ProcessDealsRequest) (*ProcessDealsResponse, error)
	ProcessResponses(context.Context, *ProcessResponsesRequest) (*ProcessResponsesResponse, error)
	ProcessJustification(context.Context, *ProcessJustificationRequest) (*ProcessJustificationResponse, error)
	FinalizeDKG(context.Context, *FinalizeDKGRequest) (*FinalizeDKGResponse, error)
	PartialDecryptTDH2(context.Context, *PartialDecryptTDH2Request) (*PartialDecryptTDH2Response, error)
	mustEmbedUnimplementedKernelServiceServer()
}

// UnimplementedKernelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelServiceServer struct{}

func (UnimplementedKernelServiceServer) GetCodeCommitment(context.Context, *GetCodeCommitmentRequest) (*GetCodeCommitmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCodeCommitment not implemented")
}
func (UnimplementedKernelServiceServer) GenerateAndSealKey(context.Context, *GenerateAndSealKeyRequest) (*GenerateAndSealKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAndSealKey not implemented")
}
func (UnimplementedKernelServiceServer) GenerateDeals(context.Context, *GenerateDealsRequest) (*GenerateDealsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDeals not implemented")
}
func (UnimplementedKernelServiceServer) ProcessDeals(context.Context, *ProcessDealsRequest) (*ProcessDealsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessDeals not implemented")
}
func (UnimplementedKernelServiceServer) ProcessResponses(context.Context, *ProcessResponsesRequest) (*ProcessResponsesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessResponses not implemented")
}
func (UnimplementedKernelServiceServer) ProcessJustification(context.Context, *ProcessJustificationRequest) (*ProcessJustificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessJustification not implemented")
}
func (UnimplementedKernelServiceServer) FinalizeDKG(context.Context, *FinalizeDKGRequest) (*FinalizeDKGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinalizeDKG not implemented")
}
func (UnimplementedKernelServiceServer) PartialDecryptTDH2(context.Context, *PartialDecryptTDH2Request) (*PartialDecryptTDH2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PartialDecryptTDH2 not implemented")
}
func (UnimplementedKernelServiceServer) mustEmbedUnimplementedKernelServiceServer() {}
func (UnimplementedKernelServiceServer) testEmbeddedByValue()                       {}

// UnsafeKernelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelServiceServer will
// result in compilation errors.
type UnsafeKernelServiceServer interface {
	mustEmbedUnimplementedKernelServiceServer()
}

func RegisterKernelServiceServer(s grpc.ServiceRegistrar, srv KernelServiceServer) {
	// If the following call pancis, it indicates UnimplementedKernelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KernelService_ServiceDesc, srv)
}

func _KernelService_GetCodeCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCodeCommitmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).GetCodeCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_GetCodeCommitment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).GetCodeCommitment(ctx, req.(*GetCodeCommitmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_GenerateAndSealKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAndSealKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).GenerateAndSealKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_GenerateAndSealKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).GenerateAndSealKey(ctx, req.(*GenerateAndSealKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_GenerateDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).GenerateDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_GenerateDeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).GenerateDeals(ctx, req.(*GenerateDealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_ProcessDeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessDealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).ProcessDeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_ProcessDeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).ProcessDeals(ctx, req.(*ProcessDealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_ProcessResponses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessResponsesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).ProcessResponses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_ProcessResponses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).ProcessResponses(ctx, req.(*ProcessResponsesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_ProcessJustification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessJustificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).ProcessJustification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_ProcessJustification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).ProcessJustification(ctx, req.(*ProcessJustificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_FinalizeDKG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeDKGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).FinalizeDKG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_FinalizeDKG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).FinalizeDKG(ctx, req.(*FinalizeDKGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelService_PartialDecryptTDH2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartialDecryptTDH2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelServiceServer).PartialDecryptTDH2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelService_PartialDecryptTDH2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelServiceServer).PartialDecryptTDH2(ctx, req.(*PartialDecryptTDH2Request))
	}
	return interceptor(ctx, in, info, handler)
}

// KernelService_ServiceDesc is the grpc.ServiceDesc for KernelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "story.dkg.v1.types.KernelService",
	HandlerType: (*KernelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCodeCommitment",
			Handler:    _KernelService_GetCodeCommitment_Handler,
		},
		{
			MethodName: "GenerateAndSealKey",
			Handler:    _KernelService_GenerateAndSealKey_Handler,
		},
		{
			MethodName: "GenerateDeals",
			Handler:    _KernelService_GenerateDeals_Handler,
		},
		{
			MethodName: "ProcessDeals",
			Handler:    _KernelService_ProcessDeals_Handler,
		},
		{
			MethodName: "ProcessResponses",
			Handler:    _KernelService_ProcessResponses_Handler,
		},
		{
			MethodName: "ProcessJustification",
			Handler:    _KernelService_ProcessJustification_Handler,
		},
		{
			MethodName: "FinalizeDKG",
			Handler:    _KernelService_FinalizeDKG_Handler,
		},
		{
			MethodName: "PartialDecryptTDH2",
			Handler:    _KernelService_PartialDecryptTDH2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tee.proto",
}
